import { Check, Download, FileJson, FileSpreadsheet, FileText, Globe, X } from "lucide-react";
import { useEffect, useState } from "react";
import type { ExportFormat, ExtractedData } from "../types";
import { formatExport, generateFilename } from "../utils/exporters";

interface ExportFormatModalProps {
	isOpen: boolean;
	onClose: () => void;
	data: ExtractedData[];
	onExportComplete: (data: ExtractedData[], format: ExportFormat, filename: string) => Promise<void> | void;
}

const FORMAT_OPTIONS: Array<{
	value: ExportFormat;
	label: string;
	icon: React.ComponentType<{ className?: string }>;
	extension: string;
}> = [
	{
		value: "json",
		label: "JSON",
		icon: FileJson,
		extension: ".json",
	},
	{
		value: "markdown",
		label: "Markdown",
		icon: FileText,
		extension: ".md",
	},
	{
		value: "text",
		label: "Plain Text",
		icon: FileText,
		extension: ".txt",
	},
	{
		value: "csv",
		label: "CSV",
		icon: FileSpreadsheet,
		extension: ".csv",
	},
	{
		value: "html",
		label: "HTML",
		icon: Globe,
		extension: ".html",
	},
];

export function ExportFormatModal({ isOpen, onClose, data, onExportComplete }: ExportFormatModalProps) {
	const [selectedFormat, setSelectedFormat] = useState<ExportFormat>("json");
	const [filename, setFilename] = useState("");
	const [preview, setPreview] = useState("");
	const [isExporting, setIsExporting] = useState(false);
	// Track whether the filename was auto-generated or user-typed
	const [isFilenameAutoGenerated, setIsFilenameAutoGenerated] = useState(true);

	// Update preview and filename when format or data changes
	useEffect(() => {
		if (data.length > 0) {
			const formatted = formatExport(data, selectedFormat);
			// Show first 500 characters as preview
			setPreview(formatted.slice(0, 500) + (formatted.length > 500 ? "\n\n..." : ""));

			// Only update filename if it was auto-generated (not user-typed)
			if (isFilenameAutoGenerated) {
				setFilename(generateFilename(selectedFormat));
			}
		} else {
			setPreview("No data to export");
		}
	}, [selectedFormat, data, isFilenameAutoGenerated]);

	const handleFilenameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
		setFilename(e.target.value);
		setIsFilenameAutoGenerated(false);
	};

	const handleExport = async () => {
		if (data.length === 0) return;

		setIsExporting(true);

		try {
			await onExportComplete(data, selectedFormat, filename);
			onClose();
		} catch (err) {
			console.error("Export failed:", err);
			throw err; // Re-throw so parent can handle error display
		} finally {
			setIsExporting(false);
		}
	};

	const handleKeyDown = (e: React.KeyboardEvent) => {
		if (e.key === "Escape") {
			onClose();
		}
	};

	if (!isOpen) return null;

	const selectedFormatOption = FORMAT_OPTIONS.find((opt) => opt.value === selectedFormat);

	return (
		<div className="fixed inset-0 z-50 flex flex-col bg-black/60 backdrop-blur-sm" onKeyDown={handleKeyDown}>
			<div className="glass-heavy w-full h-full flex flex-col shadow-2xl animate-in slide-in-from-bottom-4 duration-300">
				{/* Header */}
				<div className="flex items-center justify-between p-4 border-b border-white/10 shrink-0">
					<h2 className="text-lg font-semibold text-glass-primary">Export Format</h2>
					<button
						onClick={onClose}
						className="p-2 rounded-lg glass-hover text-glass-secondary hover:text-glass-primary transition-colors"
						aria-label="Close"
					>
						<X className="w-5 h-5" />
					</button>
				</div>

				{/* Scrollable Content */}
				<div className="flex-1 overflow-y-auto p-4 space-y-6">
					{/* Format Selection (Vertical List) */}
					<div>
						<div className="flex flex-col gap-2">
							{FORMAT_OPTIONS.map((option) => {
								const Icon = option.icon;
								const isSelected = selectedFormat === option.value;
								return (
									<button
										key={option.value}
										onClick={() => setSelectedFormat(option.value)}
										className={`
                      flex items-center justify-between p-3.5 rounded-xl transition-all duration-200 w-full group
                      ${
												isSelected
													? "glass-teal border-teal-400/30 text-white shadow-lg"
													: "glass-medium border-white/5 text-glass-secondary hover:bg-white/5 hover:border-white/20"
											}
                    `}
									>
										<div className="flex items-center gap-3">
											<div
												className={`
                        p-2 rounded-lg transition-colors
                        ${isSelected ? "bg-teal-500/20" : "bg-white/5 group-hover:bg-white/10"}
                      `}
											>
												<Icon className={`w-5 h-5 ${isSelected ? "text-teal-300" : "text-glass-secondary"}`} />
											</div>
											<span className="font-medium">{option.label}</span>
										</div>

										{isSelected && <Check className="w-5 h-5 text-teal-300" />}
									</button>
								);
							})}
						</div>
					</div>

					{/* Filename Input */}
					<div>
						<label htmlFor="filename" className="block text-sm font-medium text-glass-secondary mb-2">
							Filename
						</label>
						<input
							id="filename"
							type="text"
							value={filename}
							onChange={handleFilenameChange}
							className="w-full px-4 py-3 rounded-xl bg-white/5 border border-white/10 text-glass-primary text-sm
                       placeholder:text-glass-muted focus:outline-none focus:border-teal-400/50 focus:ring-1 focus:ring-teal-400/50
                       transition-all"
							placeholder="Enter filename..."
						/>
					</div>

					{/* Preview */}
					<div className="flex-1 flex flex-col min-h-0">
						<label className="block text-sm font-medium text-glass-secondary mb-2">Preview</label>
						<div className="glass-medium rounded-xl p-4 h-48 overflow-y-auto border border-white/10">
							<pre className="text-xs text-glass-muted whitespace-pre-wrap font-mono leading-relaxed">
								{preview || "No data to preview"}
							</pre>
						</div>
						<p className="text-xs text-glass-muted mt-2 text-center">
							{data.length} tab{data.length !== 1 ? "s" : ""} • {selectedFormatOption?.label.toUpperCase()}
						</p>
					</div>
				</div>

				{/* Footer */}
				<div className="flex gap-3 p-4 border-t border-white/10 bg-black/20 shrink-0">
					<button
						onClick={onClose}
						disabled={isExporting}
						className="flex-1 px-4 py-3 rounded-xl glass-heavy border border-white/10 text-glass-secondary
                     hover:border-white/20 hover:text-glass-primary transition-all disabled:opacity-50
                     font-medium glass-hover"
					>
						Cancel
					</button>
					<button
						onClick={handleExport}
						disabled={isExporting || data.length === 0}
						className="flex-1 px-4 py-3 rounded-xl glass-teal border border-teal-400/30 text-white
                     hover:scale-[1.02] transition-all disabled:opacity-50 disabled:cursor-not-allowed
                     font-medium flex items-center justify-center gap-2 shadow-lg shadow-teal-900/20"
					>
						{isExporting ? (
							<>
								<span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
								Exporting...
							</>
						) : (
							<>
								<Download className="w-5 h-5" />
								Download
							</>
						)}
					</button>
				</div>
			</div>
		</div>
	);
}
