import { useState, useEffect } from 'react';
import { X, Download, FileText, FileJson, FileSpreadsheet, Globe } from 'lucide-react';
import type { ExportFormat, ExtractedData } from '../types';
import { formatExport, generateFilename } from '../utils/exporters';

interface ExportFormatModalProps {
  isOpen: boolean;
  onClose: () => void;
  data: ExtractedData[];
  onExportComplete: (data: ExtractedData[], format: ExportFormat, filename: string) => Promise<void> | void;
}

const FORMAT_OPTIONS: Array<{
  value: ExportFormat;
  label: string;
  icon: React.ComponentType<{ className?: string }>;
  description: string;
  extension: string;
}> = [
  {
    value: 'json',
    label: 'JSON',
    icon: FileJson,
    description: 'Structured data format',
    extension: '.json',
  },
  {
    value: 'markdown',
    label: 'Markdown',
    icon: FileText,
    description: 'Formatted text with headers',
    extension: '.md',
  },
  {
    value: 'text',
    label: 'Plain Text',
    icon: FileText,
    description: 'Simple text without formatting',
    extension: '.txt',
  },
  {
    value: 'csv',
    label: 'CSV',
    icon: FileSpreadsheet,
    description: 'Spreadsheet-compatible format',
    extension: '.csv',
  },
  {
    value: 'html',
    label: 'HTML',
    icon: Globe,
    description: 'Styled HTML document',
    extension: '.html',
  },
];

export function ExportFormatModal({ isOpen, onClose, data, onExportComplete }: ExportFormatModalProps) {
  const [selectedFormat, setSelectedFormat] = useState<ExportFormat>('json');
  const [filename, setFilename] = useState('');
  const [preview, setPreview] = useState('');
  const [isExporting, setIsExporting] = useState(false);
  // Track whether the filename was auto-generated or user-typed
  const [isFilenameAutoGenerated, setIsFilenameAutoGenerated] = useState(true);

  // Update preview and filename when format or data changes
  useEffect(() => {
    if (data.length > 0) {
      const formatted = formatExport(data, selectedFormat);
      // Show first 500 characters as preview
      setPreview(formatted.slice(0, 500) + (formatted.length > 500 ? '\n\n...' : ''));

      // Only update filename if it was auto-generated (not user-typed)
      if (isFilenameAutoGenerated) {
        setFilename(generateFilename(selectedFormat));
      }
    } else {
      setPreview('No data to export');
    }
  }, [selectedFormat, data, isFilenameAutoGenerated]);

  const handleFilenameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFilename(e.target.value);
    setIsFilenameAutoGenerated(false);
  };

  const handleExport = async () => {
    if (data.length === 0) return;

    setIsExporting(true);

    try {
      await onExportComplete(data, selectedFormat, filename);
      onClose();
    } catch (err) {
      console.error('Export failed:', err);
      throw err; // Re-throw so parent can handle error display
    } finally {
      setIsExporting(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Escape') {
      onClose();
    }
  };

  if (!isOpen) return null;

  const selectedFormatOption = FORMAT_OPTIONS.find(opt => opt.value === selectedFormat);

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm"
      onKeyDown={handleKeyDown}
    >
      <div className="glass-heavy w-full max-w-md rounded-2xl shadow-2xl animate-in fade-in slide-in-from-bottom-4 duration-300">
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-white/10">
          <h2 className="text-lg font-semibold text-glass-primary">Export Format</h2>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg glass-hover text-glass-secondary hover:text-glass-primary transition-colors"
            aria-label="Close"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-5 space-y-5">
          {/* Format Selection */}
          <div>
            <label className="block text-sm font-medium text-glass-secondary mb-2.5">
              Export Format
            </label>
            <div className="grid grid-cols-2 gap-2">
              {FORMAT_OPTIONS.map((option) => {
                const Icon = option.icon;
                const isSelected = selectedFormat === option.value;
                return (
                  <button
                    key={option.value}
                    onClick={() => setSelectedFormat(option.value)}
                    className={`
                      flex flex-col items-start p-3 rounded-xl text-left transition-all duration-200
                      ${isSelected
                        ? 'glass-teal border-teal-400/30 text-white'
                        : 'glass-heavy border-white/10 text-glass-secondary hover:border-white/20'
                      }
                    `}
                  >
                    <div className="flex items-center gap-2 w-full">
                      <Icon className={`w-4 h-4 ${isSelected ? 'text-teal-300' : ''}`} />
                      <span className="font-medium text-sm">{option.label}</span>
                    </div>
                    <span className="text-xs text-glass-muted mt-1">{option.description}</span>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Filename Input */}
          <div>
            <label htmlFor="filename" className="block text-sm font-medium text-glass-secondary mb-2.5">
              Filename
            </label>
            <input
              id="filename"
              type="text"
              value={filename}
              onChange={handleFilenameChange}
              className="w-full px-3 py-2.5 rounded-lg bg-white/5 border border-white/10 text-glass-primary text-sm
                       placeholder:text-glass-muted focus:outline-none focus:border-teal-400/50 focus:ring-1 focus:ring-teal-400/50
                       transition-all"
              placeholder="Enter filename..."
            />
          </div>

          {/* Preview */}
          <div>
            <label className="block text-sm font-medium text-glass-secondary mb-2.5">
              Preview
            </label>
            <div className="glass-medium rounded-lg p-3 h-32 overflow-y-auto">
              <pre className="text-xs text-glass-muted whitespace-pre-wrap font-mono">
                {preview || 'No data to preview'}
              </pre>
            </div>
            <p className="text-xs text-glass-muted mt-1.5">
              {data.length} tab{data.length !== 1 ? 's' : ''} • {selectedFormatOption?.label.toUpperCase()} • Download as File
            </p>
          </div>
        </div>

        {/* Footer */}
        <div className="flex gap-3 p-5 border-t border-white/10">
          <button
            onClick={onClose}
            disabled={isExporting}
            className="flex-1 px-4 py-2.5 rounded-lg glass-heavy border border-white/10 text-glass-secondary
                     hover:border-white/20 hover:text-glass-primary transition-all disabled:opacity-50
                     font-medium text-sm glass-hover"
          >
            Cancel
          </button>
          <button
            onClick={handleExport}
            disabled={isExporting || data.length === 0}
            className="flex-1 px-4 py-2.5 rounded-lg glass-teal border border-teal-400/30 text-white
                     hover:scale-[1.02] transition-all disabled:opacity-50 disabled:cursor-not-allowed
                     font-medium text-sm flex items-center justify-center gap-2"
          >
            {isExporting ? (
              <>
                <span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                Exporting...
              </>
            ) : (
              <>
                <Download className="w-4 h-4" />
                Export
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}
